---
title: 'Lecture5 : Cluster Analysis'
author: "KIM SANG HYUN(202211545)"
date: "2025-05-08"
output: 
  github_document:
    toc: yes
---

## 05. Cluster Analysis {style="color : blue"}

```{r}
library(multtest)
library(genefilter)
library(ALL)
library(gplots)
library(ISLR2)
```

```{r}
data(golub, package = "multtest")
cyclins <- grep("Cyclin", golub.gnames[,2])
golub.gnames[cyclins, 2]
golub[cyclins, ]
dist.cyclin <- dist(golub[cyclins, ], method="euclidean")
dist.cyclin
distanceMatrix <- as.matrix(dist.cyclin)
rownames(distanceMatrix) <- golub.gnames[cyclins, 3]
colnames(distanceMatrix) <- golub.gnames[cyclins, 3]
distanceMatrix[1:5, 1:5]
```

```{r}
library(genefilter)
library(ALL)
data(ALL)
closeto1389_at <- genefinder(ALL, "1389_at", 10, method="euc")
closeto1389_at
```

-   index 번호하고 거리하고 넘겨줌

```{r}
w <- featureNames(ALL)[closeto1389_at[[1]]$indices]
data.frame(genes=w, distance=closeto1389_at[[1]]$dists)
```

### K means

```{r}
set.seed(111)
x1 <- matrix(rnorm(100, 0, 0.5), ncol=2)
x2 <- matrix(rnorm(100, 2, 0.5), ncol=2)
data <- rbind(x1, x2)
```

-   데이터 구조 확인하기

-   `nstart` : 몇 번 반복할 것인가..?

```{r}
cl <- kmeans(data, 2, nstart=20)
cl
```

```{r}
plot(data, col=cl$cluster, pch=19, xlab="X1", ylab="X2",
main="K-Means Clustering Results with K=2")
points(cl$centers, col=1:2, pch=8, cex=4)
```

```{r}
cl <- kmeans(data, 3, nstart=20)
plot(data, col=cl$cluster, pch=19, xlab="X1", ylab="X2",
main="K-Means Clustering Results with K=3")
points(cl$centers, col=1:2, pch=8, cex=4)
```

```{r}
set.seed(111)
par(mfrow=c(1, 2))
cl <- kmeans(data, 3, nstart=1)

tv <- round(cl$tot.withinss, 3)
plot(data, col=cl$cluster, pch=19, xlab="X1", ylab="X2",
main=paste("(", tv, ")"))
points(cl$centers, col=1:2, pch=8, cex=4)
cl <- kmeans(data, 3, nstart=20)
tv <- round(cl$tot.withinss, 3)
plot(data, col=cl$cluster, pch=19, xlab="X1", ylab="X2",
main=paste("(", tv, ")"))
points(cl$centers, col=1:2, pch=8, cex=4)
```

```{r}
data(golub, package="multtest")
zyxin <- grep("Zyxin", golub.gnames[ ,2])
ccnd3 <- grep("CCND3", golub.gnames[ ,2])
data <- data.frame(golub[ccnd3, ], golub[zyxin, ])
colnames(data) <- c("CCND3 (Cyclin D3)", "Zyxin")
```

```{r}
cl <- kmeans(data, 2, nstart=20)
cbind(cl$cluster, golub.cl)
```

```{r}
cl
```

```{r}
plot(data, col=cl$cluster, pch=19, xlab="CCND3", ylab="Zyxin")
points(cl$centers, col=1:2, pch=8, cex=4)
```

```{r}
par(mfrow=c(1, 3))
cl <- kmeans(data, 2, nstart=20)
plot(data, col=cl$cluster, pch=19, xlab="CCND3", ylab="Zyxin",
main="K = 2")
points(cl$centers, col=1:2, pch=8, cex=4)
cl <- kmeans(data, 3, nstart=20)
plot(data, col=cl$cluster, pch=19, xlab="CCND3", ylab="Zyxin",
main="K = 3")
points(cl$centers, col=1:3, pch=8, cex=4)
cl <- kmeans(data, 4, nstart=20)
plot(data, col=cl$cluster, pch=19, xlab="CCND3", ylab="Zyxin",
main="K = 4")
points(cl$centers, col=1:4, pch=8, cex=4)
```
